### ISSUE TITLE
Exclude pre-release versions from update notifications

### ISSUE THREAD

**Issue by mplorentz** [codechimp-org/ha-menu#44]
I am getting the "A new version is available" message even though I have the latest stable version (2.1.1). I would prefer not to see this when there is a new pre-release available, only when a new stable version has been released. Maybe a checkbox could allow users to opt-in to pre-release update notifications.

**Comment by andrew-codechimp** [comment]
Github's releases atom feed which I use doesn't distinguish pre-releases so at the moment I can't do that but looking at ways to improve the update mechanism.

**Comment by andrew-codechimp** [comment]
Version 2.2.1 now has an opt-in checkbox for pre-releases.
