### ISSUE TITLE
Open Home Assistant

### ISSUE THREAD

**Issue by niccolobusato** [codechimp-org/ha-menu#52]
Idea:

Open Home Assistant button should be "programmable" to let user decide if open HA on default browser or use the new HA App

**Comment by andrew-codechimp** [comment]
Which new HA app?  I've seen a few web wrappers over the years but nothing official.

**Comment by niccolobusato** [comment]
this one, is still in alpha but.. https://github.com/home-assistant/iOS/releases/tag/mac%2F2020.6%2F10

**Comment by andrew-codechimp** [comment]
Now that's interesting, I was just thinking about an automation of when my Mac's awake and that will do it.
Will certainly look into how I can make a switch and launch that instead.

**Comment by niccolobusato** [comment]
well now tell me more about your automation idea.. can be useful for everyone?

**Comment by andrew-codechimp** [comment]
The Mac HA Assistant app will allow me to add the Active state of my Mac into an overall state of whether I'm awake. With a multiple occupancy household there's certain lights/motion sensors I only want active when everyone is awake and I'm slowly building out how I detect this reliably.  Phone off charge using the iOS Assistant App is a good one but not foolproof.

**Comment by andrew-codechimp** [comment]
Just released version 2.4.0 which checks for the HA app and opens that, otherwise falls back to the website.
https://github.com/codechimp-org/ha-menu/releases/tag/2.4.0
