### ISSUE TITLE
No authorization: what is happening?

### ISSUE THREAD

**Issue by iAmRenzo** [codechimp-org/ha-menu#54]
I enabled a token, but it seems that I am not able to connect.
Home Assistant logs unauthorised requests though: Login attempt or request with invalid authentication from 192.168.1.10 (192.168.1.10) (HA%20Menu/24 CFNetwork/1207.2 Darwin/20.1.0)

<img width="425" alt="Schermafbeelding 2020-12-15 om 09 47 38" src="https://user-images.githubusercontent.com/1183790/102192314-e6af0100-3eba-11eb-8b82-3af9a0e10cc7.png">

**Comment by andrew-codechimp** [comment]
The fact that HA is logging requests is a good sign that the server details are correct. Strange about the Token though, I'd suggest deleting/recreating the token within HA and watching out for spaces when you paste it into HA Menu.
