### ISSUE TITLE
Feature: Send notification when HA server disconnects

### ISSUE THREAD

**Issue by thibmaek** [codechimp-org/ha-menu#58]
I've tried looking at the code, but with my limited knowledge of Swift had no clue how or where to contribute this myself. If you could point me in a direction, I could try and submit a PR myself :)

# Use case

My HA server automatically restarts when I push to my Github repo which stores my HA config. It would be very useful to be notified when the server restarts/goes down. Since your app already connects to HA, I figured it might be easy to just send a native mac notification whenever that connection would drop and then maybe also when it connects back?

I previously tried covering this via Gotify but they have no mac application.

# Examples

- Visual Studio Code extension for HA does this.
- Current iOS and Mac app will show a banner on server disconnect

**Comment by andrew-codechimp** [comment]
HA Menu does not keep an active connection to HA so cannot monitor the server status, whilst possible this would require a significant change to how the app works.  The app's design is to quickly see/change states and I'm not sure if I want to head into a more general purpose solution when the official HA app will do this.

**Comment by thibmaek** [comment]
Got it. Feel free to close the issue if you like then.
