### ISSUE TITLE
Current release 2.5.1 (26) crashes daily

### ISSUE THREAD

**Issue by xstrex** [codechimp-org/ha-menu#59]
The current release of the app crashes daily. 
version: 2.5.1 (26)
OS: MacOS 12.1

Happy to provide logs, if you can direct me to them.

**Comment by andrew-codechimp** [comment]
Just updated to 12.1 myself and haven't had issues.
You should be able to see some logs in the Console app under Crash Reports then looking for HA Menu under the Process Name.
