### ISSUE TITLE
Feature Request: Add Support for Cover Entities

### ISSUE THREAD

**Issue by alexmerm** [codechimp-org/ha-menu#60]
Basically just add the ability to turn on/off covers. If they're at all open they can be marked "on" and otherwise be marked as "off." Would be very useful for smart blinds, etc.

**Comment by andrew-codechimp** [comment]
Just had a look at covers, I don't use them myself but certainly possible, I'll add them to my todo list.

**Comment by alexmerm** [comment]
Thanks! Love the app.

**Comment by andrew-codechimp** [comment]
I have just released a beta supporting Covers.
I don't have any covers myself to test but they were very similar to existing switches for toggling open/closed so please try the beta here and let me know if it works.
https://github.com/codechimp-org/ha-menu/releases/tag/2.6.0beta

**Comment by andrew-codechimp** [comment]
Released out of beta with version 2.6.2

**Comment by alexmerm** [comment]
Sorry didn't see these messages, but I just tried it out and it works great! thanks so much!
