### ISSUE TITLE
Only show selected entities

### ISSUE THREAD

**Issue by krmax44** [codechimp-org/ha-menu#63]
With many devices, the list becomes easily cluttered. It would be awesome if I could select a handful of entities, that are then shown in the list.

**Comment by andrew-codechimp** [comment]
You can do this by creating groups within HA's groups.yaml then choosing to show those groups only as explained in the readme for this project.

**Comment by krmax44** [comment]
That doesn't work for scenes though, for example.

**Comment by andrew-codechimp** [comment]
True, I do have long term plans to add an entity picker which will solve it for scenes.
That won't be for a while though as I want to wait for SwiftUI for MacOS to get more feature complete and re-write it.
