### ISSUE TITLE
Feature Request: Values in dropdown?

### ISSUE THREAD

**Issue by daven1985** [codechimp-org/ha-menu#66]
Sorry if this is the wrong place, I couldn't see another way to ask.

Is it possible to just get a value in the dropdown, would love to be able to click on your amazing app, then say Temps and have it list my temps from sensors around my house.

Cheers.

**Comment by andrew-codechimp** [comment]
This is the right place for this.

You can add sensor values such as temperatures, just create a group within your HA groups.yaml and include the sensor, then within HA Menu just tick that group to include it in the dropdown.
The readme gives an example of how to do this at the bottom.
