### ISSUE TITLE
macOS Sonoma bug

### ISSUE THREAD

**Issue by AnthonyMaiorani** [codechimp-org/ha-menu#69]
After updating to macOS Sonoma from Ventura, I'm encountering a bug with HA Menu. 

The first 5 times opening the HA Menu after launching the application, it behaves as expected. 
<img width="253" alt="image" src="https://github.com/codechimp-org/ha-menu/assets/22204764/f802e5f1-b3bf-47f2-8861-5b01c8eb4964">
The sixth time, the menu width will shrink so that not all text will fit.
<img width="197" alt="image" src="https://github.com/codechimp-org/ha-menu/assets/22204764/a6f76544-4669-4359-b819-30021d92d363">
The seventh time, the menu width will shrink to an unusably small width. 
<img width="84" alt="image" src="https://github.com/codechimp-org/ha-menu/assets/22204764/b3867ffc-2f26-44bb-899a-32fb9fd3eb3b">
HA menu will remain this way until the application is restarted. This is consistently reproducible on my machine.

**Comment by andrew-codechimp** [comment]
Thanks for the report, I will not be using Sonoma until it's officially release and I'll investigate then.
I'm just using standard MacOS menu calls so that's a strange one, hopefully fixed with the official release.

**Comment by andrew-codechimp** [comment]
A beta release should fix this here
https://github.com/codechimp-org/ha-menu/releases/tag/2.7.1beta

**Comment by AnthonyMaiorani** [comment]
Thanks, that fixed it for me! 

I did guess it was related to macOS not liking the menu items being changed while opening it, definitely a strange one
